#ifndef STM32_LIGHTING_CONTROLLER_ADDRESSABLETASK_H
#define STM32_LIGHTING_CONTROLLER_ADDRESSABLETASK_H

void addressableTask(void * pvParameters);

#endif //STM32_LIGHTING_CONTROLLER_ADDRESSABLETASK_H
