#ifndef STM32_LIGHTING_CONTROLLER_DMXTASK_H
#define STM32_LIGHTING_CONTROLLER_DMXTASK_H

#define DMXTASK_BREAK_BIT 0x01

void dmxTask( void *pvParameters );

#endif //STM32_LIGHTING_CONTROLLER_DMXTASK_H
