#ifndef STM32_LIGHTING_CONTROLLER_PWMTASK_H
#define STM32_LIGHTING_CONTROLLER_PWMTASK_H

#define PWMTASK_TIM_BIT     0x01
#define PWMTASK_UPDATE_BIT  0x02

void pwmTask( void *pvParameters );

#endif //STM32_LIGHTING_CONTROLLER_PWMTASK_H
