#ifndef STM32_LIGHTING_CONTROLLER_SERIALTASK_H
#define STM32_LIGHTING_CONTROLLER_SERIALTASK_H

#define SERIALTASK_RX_BITS  0x01U
#define SERIALTASK__TX_BITS  0x02U

void serialReadTask(void * pvParameters);

void USART3_RXHandler();
void USART3_OERHandler();

#endif //STM32_LIGHTING_CONTROLLER_SERIALTASK_H
